version: "3.9"

services:
  wp_db:
    image: mariadb:10
    volumes:
      - ./runspace/db_data:/var/lib/mysql
      - ./db_dump.sql:/docker-entrypoint-initdb.d/snapshot.sql:ro # Change local filename to match dump
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local_root
      MYSQL_DATABASE: local_db 
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_pass
    networks:
      - wp-network #change to match line 33

  wordpress:
    depends_on:
      - local_db
    image: wordpress
      #user: "X:X"  #an optional parameter which let's you put your own local user and group id to fix permissions issues
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./files:/var/www/html
      - ./htaccess:/var/www/html/.htaccess
    networks:
      - wp-network #change to match line 33

networks:
  wp-network: #change this to something unique on your local machine
    driver: bridge
