version: "3.9"

services:
  local_db:
    image: mariadb:10
    volumes:
      - ./runspace/db_data:/var/lib/mysql
      - ./db_dump.sql:/docker-entrypoint-initdb.d/snapshot.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local_root
      MYSQL_DATABASE: local_db # Replace
      MYSQL_USER: local_user # Replace
      MYSQL_PASSWORD: local_pass # Replace
    networks:
      - wp-network

  wordpress:
    depends_on:
      - local_db
    image: wordpress
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./files:/var/www/html
      - ./htaccess:/var/www/html/.htaccess
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
